Change Win32
ffvvc/FFmpeg pull request #56
Opened 2023-04-02 19:16 UTC by Jamaika1

```
In file included from vvcdec.h:27,
                 from vvc_thread.h:26,
                 from vvc_thread.c:23:
vvc_thread.c: In function 'ff_vvc_task_run':
vvc_thread.c:577:13: error: size mismatch in argument 2 of '__atomic_compare_exchange'
  577 |             atomic_compare_exchange_strong(&ft->ret, &zero, ret);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2023-04-02 20:05 UTC, frankplow requested changes
This should probably be
```c
#ifdef _MSC_VER
```

2023-04-02 20:06 UTC, frankplow commented
Think this is meant to be a fix for the issues with MinGW cross-compilation mentioned in #55. This allows MinGW to compile (not run without errors though) but breaks compilation on gcc for Linux and introduces a warning with MSVC in the process.

2023-04-02 20:06 UTC, frankplow commented on libavcodec/vvc_thread.c
This should probably be
```
#ifdef _MSC_VER
```

2023-04-03 04:25 UTC, Jamaika1 commented on libavcodec/vvc_thread.c
> Think this is meant to be a fix for the issues with MinGW cross-compilation mentioned in #55. This allows MinGW to compile (not run without errors though) but breaks compilation on gcc for Linux and introduces a warning with MSVC in the process.

Hi fankplow

I'm an amateur who got annoyed on the doom9 forum with a lot of vvc ads and no specific types of examples of converters made.
So I decided to manually make ffmpeg with vvc, evc, htj2k, jxs, jxl, avs, avs2, avs3 converter and see if it works and how it works.
There were problems because many functions overlap from different codecs and some small bugs that I tried to fix.
It took me 1.5 months.
I converted ultravideo kvazaar addon into vvc uvg266. FFmpeg makes codecs, but only vvc, mts.
The problem is they don't play. Non-standard codec?
As for Elecard's vvc bin advertising files. Only some frames are displayed.
gcc issues and the __atomic function.
From what I can see the GNOME based librsvg addon has dropped gcc compatibility with WIN32. As a non-startable function, only MSVC is usable. So the rsvg decoder was trashed.
https://gitlab.gnome.org/GNOME/glib/-/issues/600

2023-04-03 13:36 UTC, nuomi2021 commented
> Hi @Jamaika1
> 
> > FFmpeg makes codecs, but only vvc, mts. The problem is they don't play. Non-standard codec?
> 
> VVC is a recent codec and so it is not supported in many players yet, including ffplay and VLC. It very much is standardised though.
Please work closely with us, once our code lands on FFmpeg, the entire world will get the vvc decoder :)

2023-06-22 07:26 UTC, nuomi2021 commented
@Jamaika1  replaced by https://github.com/ffvvc/FFmpeg/pull/97

2023-06-23 03:49 UTC, nuomi2021 commented
@Jamaika1 , could you help confirm the fix and close this?
thank you

2024-01-05 21:38 UTC, closed without merging