vvc_sao: Import AVX2 accelerated SAO filters from HEVC
ffvvc/FFmpeg pull request #85
Opened 2023-05-31 16:39 UTC by zackerthescar

I have imported the assembly SAO Band and Edge filters from HEVC. There are some issues

- The SAO Edge Filter currently does not work as expected
```
[FFmpeg] tests/checkasm/checkasm --test=vvc_sao
AVX2:
   vvc_sao_edge_32_8_avx2 (vvc_sao.c:138)
   vvc_sao_edge_48_8_avx2 (vvc_sao.c:138)
   vvc_sao_edge_64_8_avx2 (vvc_sao.c:138)
   vvc_sao_edge_8_10_avx2 (vvc_sao.c:138)
   vvc_sao_edge_16_10_avx2 (vvc_sao.c:138)
   vvc_sao_edge_32_10_avx2 (vvc_sao.c:138)
   vvc_sao_edge_48_10_avx2 (vvc_sao.c:138)
   vvc_sao_edge_64_10_avx2 (vvc_sao.c:138)
 - vvc_sao.sao_band [FAILED]
checkasm: 8 of 18 tests have failed
```
- We currently only have the same accelerated functions as HEVC. We do not have all functions needed to handle all possible CTU sizes for VVC. Locally, I got `vvc_sao_band_80_8_avx2` to pass `checkasm`, but not the 10-bit version, and `checkasm` causes a segfault on add other CTU sizes

- No 12-bit support.

I did some benchmarks with just the band filter enabled, and the performance between both versions are equal. Further research leads me to believe that this is expected behavior. However, `checkasm` does show pretty significant performance uplift.

```
[FFmpeg] tests/checkasm/checkasm --test=vvc_sao --benchmark                                                                                                                                 
benchmarking with native FFmpeg timers
nop: 48.4
checkasm: using random seed 815251763
AVX2:
 - vvc_sao.sao_band [OK]
checkasm: all 10 tests passed
vvc_sao_band_8_8_c: 194.9
vvc_sao_band_8_8_avx2: 41.9
vvc_sao_band_8_10_c: 230.9
vvc_sao_band_8_10_avx2: 32.9
vvc_sao_band_16_8_c: 563.9
vvc_sao_band_16_8_avx2: 131.9
vvc_sao_band_16_10_c: 788.9
vvc_sao_band_16_10_avx2: 68.9
vvc_sao_band_32_8_c: 2633.9
vvc_sao_band_32_8_avx2: 248.9
vvc_sao_band_32_10_c: 2831.9
vvc_sao_band_32_10_avx2: 257.9
vvc_sao_band_48_8_c: 5432.9
vvc_sao_band_48_8_avx2: 734.9
vvc_sao_band_48_10_c: 7511.9
vvc_sao_band_48_10_avx2: 554.9
vvc_sao_band_64_8_c: 9284.9
vvc_sao_band_64_8_avx2: 1094.9
vvc_sao_band_64_10_c: 12668.9
vvc_sao_band_64_10_avx2: 1004.9
```

2023-06-01 16:46 UTC, zackerthescar commented
Figured out the segfault causing me to not be able to test the larger width functions. All band filter functions now pass `checkasm`.

```
[FFmpeg] tests/checkasm/checkasm --test=vvc_sao --benchmark                                                                                                                     main 
benchmarking with native FFmpeg timers
nop: 48.5
checkasm: using random seed 2342436099
AVX2:
 - vvc_sao.sao_band [OK]
checkasm: all 18 tests passed
vvc_sao_band_8_8_c: 257.8
vvc_sao_band_8_8_avx2: 32.8
vvc_sao_band_8_10_c: 230.8
vvc_sao_band_8_10_avx2: 32.8
vvc_sao_band_16_8_c: 761.8
vvc_sao_band_16_8_avx2: 122.8
vvc_sao_band_16_10_c: 887.8
vvc_sao_band_16_10_avx2: 68.8
vvc_sao_band_32_8_c: 2768.8
vvc_sao_band_32_8_avx2: 239.8
vvc_sao_band_32_10_c: 2786.8
vvc_sao_band_32_10_avx2: 248.8
vvc_sao_band_48_8_c: 7367.8
vvc_sao_band_48_8_avx2: 734.8
vvc_sao_band_48_10_c: 6944.8
vvc_sao_band_48_10_avx2: 563.8
vvc_sao_band_64_8_c: 12623.8
vvc_sao_band_64_8_avx2: 977.8
vvc_sao_band_64_10_c: 11831.8
vvc_sao_band_64_10_avx2: 995.8
vvc_sao_band_80_8_c: 18806.8
vvc_sao_band_80_8_avx2: 1850.8
vvc_sao_band_80_10_c: 18788.8
vvc_sao_band_80_10_avx2: 1544.8
vvc_sao_band_96_8_c: 26474.8
vvc_sao_band_96_8_avx2: 2219.8
vvc_sao_band_96_10_c: 26321.8
vvc_sao_band_96_10_avx2: 2246.8
vvc_sao_band_112_8_c: 33791.8
vvc_sao_band_112_8_avx2: 4199.8
vvc_sao_band_112_10_c: 33728.8
vvc_sao_band_112_10_avx2: 3047.8
vvc_sao_band_128_8_c: 44015.8
vvc_sao_band_128_8_avx2: 3929.8
vvc_sao_band_128_10_c: 43727.8
vvc_sao_band_128_10_avx2: 3965.8
```

| Test File                                     | C      | AVX2   | %     |
|-----------------------------------------------|--------|--------|-------|
| BasketballDrive_1920x1080_50_10_420_37_RA.266 | 103.33 | 104.33 | 0.96% |
| RitualDance_1920x1080_60_10_420_32_LD.266     | 106.33 | 109    | 2.51% |
| RitualDance_1920x1080_60_10_420_37_RA.266     | 112    | 114    | 1.78% |
| Tango2_3840x2160_60_10_420_27_LD.266          | 27     | 27     | 0.0   |

Seems like most of the performance gain will come from the Edge filter work.

2023-06-03 20:07 UTC, zackerthescar commented
PR #84 now allows the SAO Band Filter to pass `checkasm` tests.

Benchmarks from `checkasm` below:
```
[FFmpeg] tests/checkasm/checkasm --test=vvc_sao --benchmark                                                                                                                                   
benchmarking with native FFmpeg timers
nop: 54.2
checkasm: using random seed 2747014212
AVX2:
 - vvc_sao.sao_band [OK]
checkasm: all 27 tests passed
vvc_sao_band_8_8_c: 193.4
vvc_sao_band_8_8_avx2: 40.4
vvc_sao_band_8_10_c: 238.4
vvc_sao_band_8_10_avx2: 40.4
vvc_sao_band_8_12_c: 193.4
vvc_sao_band_8_12_avx2: 49.4
vvc_sao_band_16_8_c: 1012.4
vvc_sao_band_16_8_avx2: 130.4
vvc_sao_band_16_10_c: 805.4
vvc_sao_band_16_10_avx2: 76.4
vvc_sao_band_16_12_c: 598.4
vvc_sao_band_16_12_avx2: 76.4
vvc_sao_band_32_8_c: 2677.4
vvc_sao_band_32_8_avx2: 256.4
vvc_sao_band_32_10_c: 2929.4
vvc_sao_band_32_10_avx2: 265.4
vvc_sao_band_32_12_c: 2830.4
vvc_sao_band_32_12_avx2: 265.4
vvc_sao_band_48_8_c: 5557.4
vvc_sao_band_48_8_avx2: 760.4
vvc_sao_band_48_10_c: 7645.4
vvc_sao_band_48_10_avx2: 580.4
vvc_sao_band_48_12_c: 5692.4
vvc_sao_band_48_12_avx2: 571.4
vvc_sao_band_64_8_c: 9562.4
vvc_sao_band_64_8_avx2: 1138.4
vvc_sao_band_64_10_c: 12883.4
vvc_sao_band_64_10_avx2: 1039.4
vvc_sao_band_64_12_c: 9688.4
vvc_sao_band_64_12_avx2: 1030.4
vvc_sao_band_80_8_c: 14575.4
vvc_sao_band_80_8_avx2: 1921.4
vvc_sao_band_80_10_c: 19588.4
vvc_sao_band_80_10_avx2: 1615.4
vvc_sao_band_80_12_c: 14971.4
vvc_sao_band_80_12_avx2: 1606.4
vvc_sao_band_96_8_c: 20695.4
vvc_sao_band_96_8_avx2: 2245.4
vvc_sao_band_96_10_c: 27508.4
vvc_sao_band_96_10_avx2: 2308.4
vvc_sao_band_96_12_c: 21145.4
vvc_sao_band_96_12_avx2: 2317.4
vvc_sao_band_112_8_c: 30082.4
vvc_sao_band_112_8_avx2: 3568.4
vvc_sao_band_112_10_c: 35275.4
vvc_sao_band_112_10_avx2: 3145.4
vvc_sao_band_112_12_c: 28426.4
vvc_sao_band_112_12_avx2: 3154.4
vvc_sao_band_128_8_c: 35932.4
vvc_sao_band_128_8_avx2: 4063.4
vvc_sao_band_128_10_c: 45598.4
vvc_sao_band_128_10_avx2: 4117.4
vvc_sao_band_128_12_c: 36598.4
vvc_sao_band_128_12_avx2: 5575.4
``

2023-06-11 03:53 UTC, nuomi2021 commented on libavcodec/x86/vvcdsp_init.c
> +                c->sao.edge_filter[2] = ff_vvc_sao_edge_filter_32_8_avx2;
why we not use SAO_EDGE_INIT? 
could we leave some comment here?

2023-06-11 03:54 UTC, nuomi2021 commented on libavcodec/x86/vvc_sao.asm
> +;* Copyright (c) 2014 James Almer
HEVC->VVC
Did you change anything?
If yes, maybe you can add your name here

2023-06-11 03:57 UTC, nuomi2021 commented on libavcodec/x86/vvc_sao_10bit.asm
> +;* Copyright (c) 2014 James Almer
HEVC->VVC

2023-06-11 03:58 UTC, nuomi2021 commented
@zackerthescar  thank you for your great work.
Could you use tests/tools/perf.py to provide the Performance table?

2023-06-11 04:15 UTC, nuomi2021 commented on libavcodec/vvc/vvc_filter_template.c
> -    int16_t *sao_offset_val, const int sao_left_class, const int width, const int height)
why do we need to remove const for sao_left_class, width and height?

2023-06-11 04:18 UTC, nuomi2021 requested changes
Please rebase your patchset to two commits
1. asm code
2. check_asm
thank you

2023-06-16 14:32 UTC, nuomi2021 approved these changes

2023-06-16 14:33 UTC, merged

2023-06-16 14:33 UTC, nuomi2021 commented
thank you for your great work.
@zackerthescar